"""add aboutme'


Revision ID: c8ecc4056e65
Revises: 
Create Date: 2019-10-29 00:38:50.560193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ecc4056e65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('about_html', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('about_title', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'about_title')
    op.drop_column('admin', 'about_html')
    op.drop_column('admin', 'about')
    # ### end Alembic commands ###
